//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence_Prof
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> heure_Debut { get; set; }
        public Nullable<System.TimeSpan> heure_Fin { get; set; }
        public Nullable<System.DateTime> date_Absence { get; set; }
        public string motife { get; set; }
        public string prof { get; set; }
    
        public virtual Professeur Professeur { get; set; }
    }
}
