//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ancienne_Ecole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ancienne_Ecole()
        {
            this.Eleves = new HashSet<Eleve>();
        }
    
        public int id { get; set; }
        public string nom_Ecole_Ar { get; set; }
        public string nom_Ecole_Fr { get; set; }
        public string type_Ecole { get; set; }
        public string statut_Ecole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eleve> Eleves { get; set; }
    }
}
