//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoleDBEntities : DbContext
    {
        public EcoleDBEntities()
            : base("name=EcoleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence_Eleve> Absence_Eleve { get; set; }
        public virtual DbSet<Absence_Prof> Absence_Prof { get; set; }
        public virtual DbSet<Ancienne_Classe> Ancienne_Classe { get; set; }
        public virtual DbSet<Ancienne_Ecole> Ancienne_Ecole { get; set; }
        public virtual DbSet<Annee_Scolaire> Annee_Scolaire { get; set; }
        public virtual DbSet<Classe> Classes { get; set; }
        public virtual DbSet<Classe_Details> Classe_Details { get; set; }
        public virtual DbSet<Ecole> Ecoles { get; set; }
        public virtual DbSet<Eleve> Eleves { get; set; }
        public virtual DbSet<Emploi_Temps> Emploi_Temps { get; set; }
        public virtual DbSet<Group_Cantine> Group_Cantine { get; set; }
        public virtual DbSet<Group_Transport> Group_Transport { get; set; }
        public virtual DbSet<Matiere> Matieres { get; set; }
        public virtual DbSet<Mere> Meres { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Note_Details> Note_Details { get; set; }
        public virtual DbSet<Pere> Peres { get; set; }
        public virtual DbSet<Professeur> Professeurs { get; set; }
        public virtual DbSet<Retart_Eleve> Retart_Eleve { get; set; }
        public virtual DbSet<Retart_Prof> Retart_Prof { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<Semestre> Semestres { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tuteur> Tuteurs { get; set; }
    }
}
