//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecole
    {
        public string nom { get; set; }
        public string academie { get; set; }
        public string direction_Provinciale { get; set; }
        public string commoune { get; set; }
        public string ministere { get; set; }
        public byte[] photo { get; set; }
    }
}
