//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eleve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eleve()
        {
            this.Absence_Eleve = new HashSet<Absence_Eleve>();
            this.Classe_Details = new HashSet<Classe_Details>();
            this.Note_Details = new HashSet<Note_Details>();
            this.Notes = new HashSet<Note>();
            this.Retart_Eleve = new HashSet<Retart_Eleve>();
        }
    
        public string id { get; set; }
        public Nullable<int> num { get; set; }
        public string nom_Ar { get; set; }
        public string nom_Fr { get; set; }
        public string prenom_Ar { get; set; }
        public string prenom_Fr { get; set; }
        public Nullable<System.DateTime> date_Naissance { get; set; }
        public string lieu_Naissance_Ar { get; set; }
        public string lieu_Naissance_Fr { get; set; }
        public string sexe { get; set; }
        public byte[] photo { get; set; }
        public string password { get; set; }
        public string pere { get; set; }
        public string mere { get; set; }
        public string tuteur { get; set; }
        public string type_Tuteur { get; set; }
        public Nullable<int> cantine { get; set; }
        public Nullable<int> transport { get; set; }
        public Nullable<int> anciene_Ecole { get; set; }
        public string status { get; set; }
        public Nullable<bool> registred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absence_Eleve> Absence_Eleve { get; set; }
        public virtual Ancienne_Ecole Ancienne_Ecole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classe_Details> Classe_Details { get; set; }
        public virtual Group_Cantine Group_Cantine { get; set; }
        public virtual Group_Transport Group_Transport { get; set; }
        public virtual Mere Mere1 { get; set; }
        public virtual Pere Pere1 { get; set; }
        public virtual Tuteur Tuteur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note_Details> Note_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retart_Eleve> Retart_Eleve { get; set; }
    }
}
