//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi_Temps
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_Debut { get; set; }
        public Nullable<System.DateTime> date_Fin { get; set; }
        public string prof { get; set; }
        public string classe { get; set; }
        public string salle { get; set; }
        public string joure { get; set; }
    
        public virtual Classe Classe1 { get; set; }
        public virtual Professeur Professeur { get; set; }
        public virtual Salle Salle1 { get; set; }
    }
}
