//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Details
    {
        public string eleve { get; set; }
        public int semestere { get; set; }
        public string annee { get; set; }
        public string matiere { get; set; }
        public Nullable<double> ctrl1 { get; set; }
        public Nullable<double> ctrl2 { get; set; }
        public Nullable<double> ctrl3 { get; set; }
        public Nullable<double> ctrl4 { get; set; }
        public Nullable<double> note { get; set; }
        public Nullable<double> note_Exame { get; set; }
    
        public virtual Annee_Scolaire Annee_Scolaire { get; set; }
        public virtual Eleve Eleve1 { get; set; }
        public virtual Matiere Matiere1 { get; set; }
        public virtual Semestre Semestre { get; set; }
    }
}
